dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

brownie networks:
  # default: ganache-local
  rinkeby:
    eth_usd_pricefeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'

  mainnet-fork:
    eth_usd_pricefeed: '0xAc559F25B1619171CbC396a50854A3240b6A4e99'
